---
title: "Defining Disease: Exploring Single-Cell Gene Expression Associated with Alzheimer’s Disease"
---

This is free, open source set of materials for conducting an advanced-undergraduate lab activity exploring disease states with the Seattle Alzheimer's Disease Atlas (SEA-AD), an open-source data set created by the Allen Institute.

These materials were developed by: Theresa McKim (University of Nevada, Reno), Shveta Parekh (Boston College), Thomas Newpher (Duke University), and Lucinda Carnell (Central Washington University), and Bob Calin-Jageman (Dominican University) in partnership in partnership with the Developing Open Neuroscience Teaching Tools Workshop offered through the [Allen Institute](https://alleninstitute.org/) Summer Workshop. The development of this lab was inspired by a fantastic activity created by Madison Meuler and Kaitlyn Casimo of the Allen Institute, with several figures and portions of the pre-lab text adapted directly from their work. A big thanks to Madison and Kaitlyn for their creativity and generosity in sharing their materials! We also thank Rachel Penton, Lauren Alfiler, Jeremy Miller, and the many people at Allen who helped support this project.

Here you will find a complete set of lab materials you can adapt for your own courses.

- These pages present the lab in html format, with each page also having a pdf version you can download.

- The github repository for this project provides these resources in Markdown format, available for you to remix and update: <https://github.com/rcalinjageman/Exploring-Disease-States-with-the-SEA-AD-project>

- For use with an LMS:

  - [This zip file](https://github.com/rcalinjageman/Exploring-Disease-States-with-the-SEA-AD-project/tree/main/common_cartridge) is a Canvas export in Common Cartridge Formate. It should enable you to import the pre-lab and lab activity, each as a stand-alone, self-paced online activity that you can customize. Enjoy, and if you use these resources, please cite their source!

- Online resources you can provide to your students

- Assessment: We provide a set of potential assessment items, both objective and self-reported, and provide Qualtrics exports you can use to collect your own assessment data [here](https://github.com/rcalinjageman/Exploring-Disease-States-with-the-SEA-AD-project/tree/main/qualtrics).

- CellxGene Explorer Tutorial: Can be provided to give a more detailed overview of how to navigate the CellxGene explorer: <https://cellxgene.cziscience.com/docs/04__Analyze%20Public%20Data/4_1__Hosted%20Tutorials> 

- Supplemental videos

  - The Allen Institute has a short webinar about this project here: <https://www.youtube.com/watch?v=QON_qTo06oM>

  - And a longer webinar here: <https://www.youtube.com/watch?v=lcS3o1N22Bc>
